### ISSUE TITLE
Request to update version of terraforming

### ISSUE THREAD

**Issue by mikemcclay** [dtan4/dockerfile-terraforming#24]
Please update the version of terraforming used in this Docker image to 0.12.0 or set it so that it will always target the latest build of terraforming. Your terraforming software is great and so having access to an up to date Docker image with the latest version in it would be awesome.

**Comment by dtan4** [comment]
Thank you for reporting! I completely forgot to update this image until now...

At #25 I updated Terraforming to v0.12.0. Please try the latest image.
